version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install -g serverless
      - npm install --save-dev serverless-wsgi serverless-python-requirements
  build:
    commands:
      - serverless deploy

cache:
  paths:
    - node_modules
